[package]
name = "test-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
backend = { path = "../backend", features = ["ssr"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1.0.140"
